spring:
  profiles:
    active: dev #自定开发环境
#debug: true
--- #dev 开发环境
spring:
  profiles: dev

  #jackson统一日期格式化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #数据库和jpa配置
  datasource:
    url: jdbc:mysql://localhost:3306/qdf?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

##################################################
# JodConverter Configuration
##################################################
jodconverter:
  enabled: true
  officeHome: C:/Program Files (x86)/OpenOffice 4
  portNumbers: 8100, 8101, 8102, 8103, 8104, 8105, 8106, 8107, 8108, 8109
  maxTasksPerProcess: 10

myshiro:
  #Redis服务器配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  #shiro和jwt相关的配置
  shiro:
    #
    redis-cache-key: "shiro:cache:"
    jwt-cache-key: "jwt:cache:"
    # AES密码加密私钥(Base64加密)
    encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==
    # JWT认证加密私钥(Base64加密)
    encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
    # AccessToken过期时间-5分钟-5*60(秒为单位)
    accessTokenExpireTime: 300
    # RefreshToken过期时间-30分钟-30*60(秒为单位)
    refreshTokenExpireTime: 1800
    # Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
    shiroCacheExpireTime: 300

#服务端口
server:
  port: 8080

--- #test 测试环境
spring:
  profiles: test

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://localhost:3306/qdf?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect

myshiro:
  #Redis服务器配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  #shiro和jwt相关的配置
  shiro:
    #
    redis-cache-key: "shiro:cache:"
    jwt-cache-key: "jwt:cache:"
    # AES密码加密私钥(Base64加密)
    encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==
    # JWT认证加密私钥(Base64加密)
    encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
    # AccessToken过期时间-5分钟-5*60(秒为单位)
    accessTokenExpireTime: 300
    # RefreshToken过期时间-30分钟-30*60(秒为单位)
    refreshTokenExpireTime: 1800
    # Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
    shiroCacheExpireTime: 300

server:
  port: 8080

--- #prod 生产环境
spring:
  profiles: prod

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://localhost:3306/qdf?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect

myshiro:
  #Redis服务器配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  #shiro和jwt相关的配置
  shiro:
    #
    redis-cache-key: "shiro:cache:"
    jwt-cache-key: "jwt:cache:"
    # AES密码加密私钥(Base64加密)
    encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==
    # JWT认证加密私钥(Base64加密)
    encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
    # AccessToken过期时间-5分钟-5*60(秒为单位)，客户端的token的过期时间，过期后再请求会收到一个新的token，下次请求带上新的token即可
    accessTokenExpireTime: 300
    # RefreshToken过期时间-30分钟-30*60(秒为单位)，过期后将从缓存中移除该token，客户端将需要重新登陆才能获取有效token并进行访问
    refreshTokenExpireTime: 1800
    # Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
    shiroCacheExpireTime: 300

server:
  port: 8080
